dist: noble
language: php

php:
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1.0'
  - '8.2'
  - '8.3'
  - '8.4'

before_install:
    - composer require --dev --no-update phpunit/phpunit ^9.5

before_script: composer install

script:
    - vendor/bin/phpunit
